name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Copilot Usage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: copilot-usage
        with:
          organization: ${{ vars.ORG }}
          github-token: ${{ secrets.TOKEN }}
          time-zone: "EST"
          csv: true
