name: CI
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - run: npm ci
      - run: npm run lint
        continue-on-error: true
      - run: npm run build
      - run: npm test
        env:
          TZ: 'America/New_York'
