name: Email Copilot Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Sunday at midnight (00:00).
permissions:
  contents: read

jobs:
  run:
    name: Copilot Usage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: austenstone/copilot-usage@main
        id: usage
        with:
          organization: ${{ vars.ORG }}
          github-token: ${{ secrets.TOKEN }}
      - uses: austenstone/job-summary@67b7e1f68ee55e44d073ab7354e7b580cd09567c # v2.0
        id: pdf
        with:
          name: copilot-usage
      - uses: dawidd6/action-send-mail@94de994a9f6fffee200243214e17002e2920bb59 # v18
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          from: ${{ secrets.EMAIL }}
          to: ${{ secrets.EMAIL }} # Recipient email
          subject: "Copilot Usage Report (${{ steps.usage.outputs.since }} - ${{ steps.usage.outputs.until }})"
          html_body: |
            <!DOCTYPE html>
            <html>
            
            <body>
              <h1>Copilot Usage Report</h1>
              <p>Attached is the Copilot Usage Report for ${{ steps.usage.outputs.since }} - ${{ steps.usage.outputs.until }}!</p>
              <p>
                <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#:~:text=Copilot%20Usage%20summary">View the full report on
                  GitHub.com</a>
              </p>

              ${{ steps.pdf.outputs.job-summary-html }}
              
            </body>
            
            </html>
          attachments: ${{ steps.pdf.outputs.pdf-file }}