name: Usage
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Copilot Usage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
        id: copilot-usage
        with:
          organization: ${{ vars.ORG }}
          github-token: ${{ secrets.TOKEN }}
          time-zone: "EST"
          json: true
