name: Usage Teams
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Copilot Usage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          organization: ${{ secrets.ORG }}
          team: corporate-solutions-eng
          github-token: ${{ secrets.TOKEN }}
          time-zone: "EST"
          json: true
          artifact-name: "corporate-solutions-eng-copilot-usage"
      - uses: ./
        with:
          organization: ${{ secrets.ORG }}
          team: bookstore-developers
          github-token: ${{ secrets.TOKEN }}
          time-zone: "EST"
          json: true
          artifact-name: "bookstore-developers-copilot-usage"
